site_name: Melon Notes
site_description: "Public notes, powered by SilverBullet & MkDocs"
site_url: https://melvin-suter.github.io/silver-site/
docs_dir: docs

theme:
  name: terminal
  features: []

plugins:
- search
- blog
- tags

nav:
  - Home: home.md
  - Blog:
      - blog/index.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - codehilite
  - tables

extra:
  generator: false
